version: '3'

networks:
  medical-clinic-network:

services:
  proxy:
    image: 'medical-clinic-proxy:latest'
    hostname: medical-clinic-proxy
    build:
      context: .
    ports:
      - "8090:8090"
    container_name: proxy
    depends_on:
      - app
    environment:
      - FEIGN_CLIENT_MEDICAL-CLINIC-CLIENT_URL=http://medical-clinic:8080

  app:
    image: 'medical-clinic:latest'
    hostname: medical-clinic
    ports:
      - "8080:8080"
    container_name: app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/medical-clinic-db
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate

  db:
    image: 'postgres:13.1-alpine'
    ports:
      - "5432:5432"
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - POSTGRES_DB=medical-clinic-db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'lukasz@mail.com'
      PGADMIN_DEFAULT_PASSWORD: "sa1234"
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local